DROP DATABASE IF EXISTS `fit_kaloria`;

CREATE DATABASE IF NOT EXISTS `fit_kaloria` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE `fit_kaloria`;

CREATE TABLE IF NOT EXISTS `DISHES` 
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `name` VARCHAR(30),
  `ID_author`  INTEGER,
  `amount_calories` FLOAT,
  `amount_portion` INTEGER,
  `recommend_portion` INTEGER
);

CREATE INDEX IF NOT EXISTS `DISHES_INDEX` ON `DISHES`(`name`);

CREATE TABLE IF NOT EXISTS `DISHES_DAY` 
(
  `ID` INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
  `ID_meal` INTEGER,
  `ID_user` INTEGER,
  `date` TIMESTAMP DEFAULT current_timestamp(),
  `ID_dishes` INTEGER
);

CREATE TABLE IF NOT EXISTS  `DISHES_INGREDIENTS`
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `ID_dishes` INTEGER,
  `ID_ingredients` INTEGER
);

CREATE TABLE IF NOT EXISTS `FITNESS_PLAN` 
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `name` VARCHAR(30),
  `ID_author` INTEGER,
  `type` VARCHAR(128),
  `tags` VARCHAR(256),
  `description` VARCHAR(512),
  `daily_protein` FLOAT,
  `daily_carbohydrates` FLOAT,
  `daily_fat` FLOAT,
  `num_dishes` INTEGER,
  `energy_aim` FLOAT
);

CREATE INDEX IF NOT EXISTS `FITNESS_PLAN_INDEX` ON `FITNESS_PLAN`(`name`);

CREATE TABLE IF NOT EXISTS `FITNESS_PLAN_DISHES_INGREDIENTS` 
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `ID_fitness_plan` INTEGER,
  `ID_dishes` INTEGER,
  `ID_meal` INTEGER
);

CREATE TABLE IF NOT EXISTS `INGREDIENTS` 
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `name` VARCHAR(50),
  `calories` FLOAT,
  `protein` FLOAT,
  `carbohydrates` FLOAT,
  `fat` FLOAT,
  `fat_full` FLOAT,
  `fat_uunfill` FLOAT
);

CREATE INDEX IF NOT EXISTS `INGREDIENTS_INDEX` ON `INGREDIENTS`(`ID`, `name`);

CREATE TABLE IF NOT EXISTS `MEAL` 
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `name` VARCHAR(100)
);

CREATE TABLE `NEWSLETTER` 
(
  `ID` INTEGER PRIMARY KEY AUTO_INCREMENT UNIQUE,
  `ID_user` INTEGER
);

CREATE TABLE `USERS` 
(
  `ID` INTEGER AUTO_INCREMENT UNIQUE PRIMARY KEY,
  `loginU` VARCHAR(50),
  `email` VARCHAR(100),
  `firstname` VARCHAR(30),
  `lastname` VARCHAR(60),
  `_password` VARCHAR(128),
  `weight` FLOAT,
  `created_at` DATETIME NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
);

CREATE INDEX IF NOT EXISTS `USERS_INDEX` ON `USERS`(`ID`, `email`, `loginU`);

CREATE TABLE `USERS_FITNESS_PLAN` 
(
  `ID` INTEGER PRIMARY KEY UNIQUE AUTO_INCREMENT,
  `ID_fitness_plan` INTEGER,
  `ID_user` INTEGER
);

-- Foreign keys --
ALTER TABLE `FITNESS_PLAN`
ADD CONSTRAINT FK_fitnessplanusers
FOREIGN KEY (`ID_author`) REFERENCES `USERS`(`ID`);

ALTER TABLE `DISHES_INGREDIENTS`
ADD CONSTRAINT FK_dishesingredientsdishes
FOREIGN KEY (`ID_dishes`) REFERENCES `DISHES`(`ID`);

ALTER TABLE `DISHES_INGREDIENTS`
ADD CONSTRAINT FK_dishesingredientsingredients
FOREIGN KEY (`ID_ingredients`) REFERENCES `INGREDIENTS`(`ID`);

ALTER TABLE `DISHES_DAY`
ADD CONSTRAINT FK_dishesdaydishes
FOREIGN KEY (`ID_dishes`) REFERENCES `DISHES`(`ID`);

ALTER TABLE `DISHES_DAY`
ADD CONSTRAINT FK_dishesdayusers
FOREIGN KEY (`ID_user`) REFERENCES `USERS`(`ID`);

ALTER TABLE `DISHES_DAY`
ADD CONSTRAINT FK_dishesdaymeal
FOREIGN KEY (`ID_meal`) REFERENCES `MEAL`(`ID`);

ALTER TABLE `NEWSLETTER`
ADD CONSTRAINT FK_newsletterusers
FOREIGN KEY (`ID_user`) REFERENCES `USERS`(`ID`);

ALTER TABLE `FITNESS_PLAN_DISHES_INGREDIENTS`
ADD CONSTRAINT FK_fitnessplandishesingredientsmeal
FOREIGN KEY (`ID_meal`) REFERENCES `MEAL`(`ID`);

ALTER TABLE `FITNESS_PLAN_DISHES_INGREDIENTS`
ADD CONSTRAINT FK_fitnessplandishesingredientsdishes
FOREIGN KEY (`ID_dishes`) REFERENCES `DISHES`(`ID`);

ALTER TABLE `FITNESS_PLAN_DISHES_INGREDIENTS`
ADD CONSTRAINT FK_fitnessplandishesingredientsfitnessplan
FOREIGN KEY (`ID_fitness_plan`) REFERENCES `FITNESS_PLAN`(`ID`);

ALTER TABLE `USERS_FITNESS_PLAN`
ADD CONSTRAINT FK_usersfitnessplanusers
FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID`);

ALTER TABLE `USERS_FITNESS_PLAN`
ADD CONSTRAINT FK_usersfitnessplanfitnessplan
FOREIGN KEY (`ID_fitness_plan`) REFERENCES `FITNESS_PLAN`(`ID`);